event/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^home/$', views.home, name='home'),
    url(r'^event/$', views.event_list, name='event_list'),
    url(r'^user_event/$', views.user_event_list, name='user_event_list'),
    url(r'^public_event/$', views.event_list_public, name='event_list_public'),
    url(r'^orgs/$', views.org_list, name='org_list'),
    url(r'^event/(?P<pk>\d+)/delete/$', views.event_delete, name='event_delete'),
    url(r'^event/(?P<pk>\d+)/edit/$', views.event_edit, name='event_edit'),
    url(r'^event/addhours/$', views.event_Emp_Record, name='event_addhours'),
    url(r'^event/staff_addhours/$', views.event_Staff_Record, name='staff_addhours'),
    url(r'^event/create/$', views.event_new, name='event_new'),
    url(r'^org/(?P<pk>\d+)/delete/$', views.org_delete, name='org_delete'),
    url(r'^orgs/(?P<pk>\d+)/edit/$', views.org_edit, name='org_edit'),
    url(r'^orgs/create/$', views.org_new, name='org_new'),


]

mcgb/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('event.urls', namespace='event')),
    url(r'^accounts/login/$', views.login, name='login'),
    url(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page': '/'}),
    url(r'^password_reset_form/$', views.password_reset, name='password_reset_form'),
    url(r'^password_reset/done/$', views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', views.password_reset_complete, name='password_reset_complete'),
]

event/models.py
from django.db import models
from django.utils import timezone
from django import forms
from django.contrib.auth.models import User
from django.contrib.admin.widgets import AdminDateWidget
from django.forms.fields import DateField

STATES = [
    ('Alabama', 'AL'),
    ('Alaska', 'AK'),
    ('Arizona', 'AZ'),
    ('Arkansas', 'AR'),
    ('California', 'CA'),
    ('Colorado', 'CO'),
    ('Connecticut', 'CT'),
    ('Delaware', 'DE'),
    ('Florida', 'FL'),
    ('Georgia', 'GA'),
    ('Hawaii', 'HI'),
    ('Idaho', 'ID'),
    ('Illinois', 'IL'),
    ('Indiana', 'IN'),
    ('Iowa', 'IA'),
    ('Kansas', 'KS'),
    ('Kentucky', 'KY'),
    ('Louisiana', 'LA'),
    ('Maine', 'ME'),
    ('Maryland', 'MD'),
    ('Massachusetts', 'MA'),
    ('Michigan', 'MI'),
    ('Minnesota', 'MN'),
    ('Mississippi', 'MS'),
    ('Missouri', 'MO'),
    ('Montana', 'MT'),
    ('Nebraska', 'NE'),
    ('Nevada', 'NV'),
    ('New Hampshire', 'NH'),
    ('New Jersey', 'NJ'),
    ('New Mexico', 'NM'),
    ('New York', 'NY'),
    ('North Carolina', 'NC'),
    ('North Dakota', 'ND'),
    ('Ohio', 'OH'),
    ('Oklahoma', 'OK'),
    ('Oregon', 'OR'),
    ('Pennsylvania', 'PA'),
    ('Rhode Island', 'RI'),
    ('South Carolina', 'SC'),
    ('South Dakota', 'SD'),
    ('Tennessee', 'TN'),
    ('Texas', 'TX'),
    ('Utah', 'UT'),
    ('Vermont', 'VT'),
    ('Virginia', 'VA'),
    ('Washington', 'WA'),
    ('West Virginia', 'WV'),
    ('Wisconsin', 'WI'),
    ('Wyoming', 'WY'),
    ]

TIMES = [
    ('00:00AM', '00:00'),
    ('00:30AM', '00:30'),
    ('01:00AM', '01:00'),
    ('01:30AM', '01:30'),
    ('02:00AM', '02:00'),
    ('02:30AM', '02:30'),
    ('03:00AM', '03:00'),
    ('03:30AM', '03:30'),
    ('04:00AM', '04:00'),
    ('04:30AM', '04:30'),
    ('05:00AM', '05:00'),
    ('05:30AM', '05:30'),
    ('06:00AM', '06:00'),
    ('06:30AM', '06:30'),
    ('07:00AM', '07:00'),
    ('07:30AM', '07:30'),
    ('08:00AM', '08:00'),
    ('08:30AM', '08:30'),
    ('09:00AM', '09:00'),
    ('09:30AM', '09:30'),
    ('10:00AM', '10:00'),
    ('10:30AM', '10:30'),
    ('11:00AM', '11:00'),
    ('11:30AM', '11:30'),
    ('12:00PM', '12:00'),
    ('00:30PM', '12:30'),
    ('01:00PM', '13:00'),
    ('01:30PM', '13:30'),
    ('02:00PM', '14:00'),
    ('02:30PM', '14:30'),
    ('03:00PM', '15:00'),
    ('03:30PM', '15:30'),
    ('04:00PM', '16:00'),
    ('04:30PM', '16:30'),
    ('05:00PM', '17:00'),
    ('05:30PM', '17:30'),
    ('06:00PM', '18:00'),
    ('06:30PM', '18:30'),
    ('07:00PM', '19:00'),
    ('07:30PM', '19:30'),
    ('08:00PM', '20:00'),
    ('08:30PM', '20:30'),
    ('09:00PM', '21:00'),
    ('09:30PM', '21:30'),
    ('10:00PM', '22:00'),
    ('10:30PM', '22:30'),
    ('11:00PM', '23:00'),
    ('11:30PM', '23:30'),
    ]



class Organization(models.Model):
    Org_ID = models.IntegerField(blank=False, null=False, unique=True)
    Org_Name = models.CharField(max_length=50)
    Org_Phone = models.CharField(blank=False, null=False, max_length=9)
    Org_Description = models.CharField(max_length=500)
    Org_Email = models.CharField(max_length=50)
    Org_Street = models.CharField(max_length=50)
    Org_City = models.CharField(max_length=50)
    Org_State = models.CharField(max_length=20, choices=STATES)
    Org_Postal = models.IntegerField(blank=False, null=False)

    def created(self):
        self.save()

    def __str__(self):
        return str(self.Org_ID)


class OrgContactPerson(models.Model):
    Org_ID = models.ForeignKey(Organization, related_name='orgContactPersons')
    Org_Contact_Fname = models.CharField(max_length=50)
    Org_Contact_Lname = models.CharField(max_length=50)
    Org_Contact_Phone = models.CharField(max_length=9)
    Org_contact_Email = models.CharField(max_length=50)
    Org_Contact_Position = models.CharField(max_length=50)

    def created(self):
        self.save()

    def __str__(self):
        return str(self.Org_ID)


class Event(models.Model):
    Event_ID = models.IntegerField(blank=False, null=False, unique=True)
    Org_ID = models.ForeignKey(Organization, related_name='events')
    Event_Description = models.CharField(max_length=500)
    Event_StartDate = models.DateField(default=timezone.now)
    Event_StartTime = models.CharField(max_length=10, choices=TIMES)
    Event_EndDate = models.DateField(default=timezone.now)
    Event_EndTime = models.CharField(max_length=10, choices=TIMES)
    Event_Requirement = models.CharField(max_length=50)
    Event_MaxPax = models.IntegerField(blank=False)
    Event_Street = models.CharField(max_length=50)
    Event_City = models.CharField(max_length=50)
    Event_State = models.CharField(max_length=20, choices=STATES)
    Event_Postal = models.IntegerField(blank=False, null=False)

    def created(self):
        self.save()

    def __str__(self):
        return str(self.Event_ID)




class Emp_Record(models.Model):
    username = models.ForeignKey(User, related_name='user')
    Event_ID = models.ForeignKey(Event, related_name='events')
    EmpRecord_Time = models.DecimalField(max_digits=4, decimal_places=2)

    def created(self):
        self.save()

    def __str__(self):
        return str(self.username)

event/forms.py
from django import forms
from .models import Event, Organization, Emp_Record
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.admin import widgets


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ('Event_ID', 'Org_ID', 'Event_Description', 'Event_StartDate', 'Event_StartTime', 'Event_EndDate',
                  'Event_EndTime',
                  'Event_Requirement', 'Event_MaxPax', 'Event_Street', 'Event_City', 'Event_State',
                  'Event_Postal')

    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)
        self.fields['Event_StartDate'].widget = widgets.AdminDateWidget()
        self.fields['Event_EndDate'].widget = widgets.AdminDateWidget()


class OrgForm(forms.ModelForm):
    class Meta:
        model = Organization
        fields = ('Org_ID', 'Org_Name', 'Org_Phone', 'Org_Description', 'Org_Email', 'Org_Street',
                  'Org_City', 'Org_State', 'Org_Postal')


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2',)



class Emp_RecordForm(forms.ModelForm):
    class Meta:
        model = Emp_Record
        fields = ('username', 'Event_ID', 'EmpRecord_Time')

class Staff_RecordForm(forms.ModelForm):
    class Meta:
        model = Emp_Record
        fields = ('Event_ID', 'EmpRecord_Time')

event/views.py
from django.utils import timezone
from .models import *
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate
from .forms import *
from django.db.models import Sum


def home(request):
    return render(request, 'event/home.html',
                  {'event': home})


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return render(request, 'event/home.html',
                  {'event': home})
    else:
        form = SignUpForm()
    return render(request, 'event/signup.html', {'form': form})




def event_list_public(request):
    events = Event.objects.filter()
    return render(request, 'event/event_list_public.html',
                  {'events': events})



@login_required
def user_event_list(request):
    events = Event.objects.filter()
    return render(request, 'event/user_event_list.html',
                  {'events': events})




@login_required
def event_list(request):
    events = Event.objects.filter()
    return render(request, 'event/event_list.html',
                  {'events': events})


@login_required
def org_list(request):
    orgs = Organization.objects.filter()
    return render(request, 'event/org_list.html',
                  {'orgs': orgs})


@login_required
def event_new(request):
    if request.method == "POST":
        form = EventForm(request.POST)
        if form.is_valid():
            event = form.save(commit=False)
            event.created_date = timezone.now()
            event.save()
            events = Event.objects.filter()
            return render(request, 'event/event_list.html',
                          {'events': events})
    else:
        form = EventForm()
    return render(request, 'event/event_new.html', {'form': form})




@login_required
def event_edit(request, pk):
    event = get_object_or_404(Event, pk=pk)
    if request.method == "POST":
        # update
        form = EventForm(request.POST, instance=event)
        if form.is_valid():
            event = form.save(commit=False)
            event.save()
            event = Event.objects.filter()
            return render(request, 'event/event_list.html', {'events': event})
    else:
        form = EventForm(instance=event)
    return render(request, 'event/event_edit.html', {'form': form})





@login_required
def event_Emp_Record(request):
    record = get_object_or_404(Event, Event_ID=1)
    if request.method == "POST":
        # update
        form = Emp_RecordForm(request.POST)
        if form.is_valid():
            record = form.save(commit=False)
            record.save()
            events = Event.objects.filter()
            return render(request, 'event/event_list.html', {'events': events})
    else:
        form = Emp_RecordForm(instance=record)
    return render(request, 'event/event_addhour.html', {'form': form})


@login_required
def event_Staff_Record(request):
    Emp_Record = get_object_or_404(Event, Event_ID=1)
    if request.method == "POST":
        form = Staff_RecordForm(request.POST)
        if form.is_valid():
            Emp_Record = form.save(commit=False)
            Emp_Record.username = request.user
            Emp_Record.save()
            events = Event.objects.filter()
            return render(request, 'event/event_list.html', {'events': events})
    else:
        form = Staff_RecordForm(instance=Emp_Record)
    return render(request, 'event/staff_addhour.html', {'form': form})





@login_required
def event_delete(request, pk):
    event = get_object_or_404(Event, pk=pk)
    event.delete()
    events = Event.objects.filter()
    return render(request, 'event/event_list.html', {'events': events})


@login_required
def org_new(request):
    if request.method == "POST":
        form = OrgForm(request.POST)
        if form.is_valid():
            org = form.save(commit=False)
            org.created_date = timezone.now()
            org.save()
            orgs = Organization.objects.filter()
            return render(request, 'event/org_list.html',
                          {'orgs': orgs})
    else:
        form = OrgForm()
    # print("Else")
    return render(request, 'event/org_new.html', {'form': form})


@login_required
def org_edit(request, pk):
    org = get_object_or_404(Organization, pk=pk)
    if request.method == "POST":
        # update
        form = OrgForm(request.POST, instance=org)
        if form.is_valid():
            org = form.save(commit=False)
            org.save()
            org = Organization.objects.filter()
            return render(request, 'event/org_list.html', {'orgs': org})
    else:
        form = OrgForm(instance=org)
    return render(request, 'event/org_edit.html', {'form': form})


@login_required
def org_delete(request, pk):
    org = get_object_or_404(Organization, pk=pk)
    org.delete()
    orgs = Organization.objects.filter()
    return render(request, 'event/org_list.html', {'orgs': orgs})

event/templates/event/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Mid-City Gives Back</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
        /* Remove the navbar's default margin-bottom and rounded borders */
        .navbar {
            margin-bottom: 0;
            border-radius: 0;
        }

        /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
        .row.content {
            height: 450px
        }

        /* Set gray background color and 100% height */
        .sidenav {
            padding-top: 20px;
            background-color: #f1f1f1;
            height: 100%;
        }

        /* Set black background color, white text and some padding */
        footer {
            background-color: #555;
            color: white;
            padding: 15px;
        }

        /* On small screens, set height to 'auto' for sidenav and grid */
        @media screen and (max-width: 767px) {
            .sidenav {
                height: auto;
                padding: 15px;
            }

            .row.content {
                height: auto;
            }
        }
    </style>
</head>
<body id="app-layout">
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">

            <!-- Collapsed Hamburger -->
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#myNavbar">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- Branding Image -->
            <a class="navbar-brand" href="/">
                Mid-City Gives Back
            </a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'event:home' %}">Home</a></li>
                <li><a href='{% url "event:event_list_public" %}'>Public Event List</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{% url 'logout' %}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                            {% if request.user.is_superuser %}
                            <li><a href="{% url 'admin:password_change' %}">Change password</a></li>
                            {% endif %}
                        </ul>
                    </li>
                {% else %}
                    <li><a href="{% url 'event:signup' %}">New User Registration</a></li>
                    <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                    <li><a href="{% url 'password_reset_form' %}">Forgot password</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<div class="content container">
    <div class="row">
        <div class="col-md-8">
            {% block content %}
               <p>Need content</p>
            {% endblock %}
        </div>
    </div>
</body>
</html>

event/templates/event/event_addhour.html
{% extends 'event/base.html' %}

{% block content %}
    <h1>Add hours</h1>
    <form method="POST" class="hour-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Update</button>
    </form>
{% endblock %}

event/templates/event/event_edit.html
{% extends 'event/base.html' %}

{% block content %}
    <h1>Edit Event</h1>
    <form method="POST" class="event-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Update</button>
    </form>
{% endblock %}

event/templates/event/event_list.html
{% extends 'event/base.html' %}


{% block content %}
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title>Mid-City Gives Back</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    </head>
    <body>
    <style>
        body {
            background-color: beige;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">Welcome!</div>
                    <div class="panel-body">
                        <p>Below is a list of all events.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <h2 style="padding-left: 15Px">Event List</h2>
    </div>
    <div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Event ID</th>
                <th>Org ID</th>
                <th>Event Description</th>
                <th>Event Start Date</th>
                <th>Event Start Time</th>
                <th>Event End Date</th>
                <th>Event End Time</th>
                <th>Event Requirement</th>
                <th>Event Capacity</th>
                {% if request.user.is_superuser %}
                <th colspan="2">Actions</th>
                {% endif %}
            </tr>
            </thead>
            <tbody>
            {% for events in events %}
                <tr>
                    <td>{{ events.Event_ID }}</td>
                    <td>{{ events.Org_ID }}</td>
                    <td>{{ events.Event_Description }}</td>
                    <td>{{ events.Event_StartDate }}</td>
                    <td>{{ events.Event_StartTime }}</td>
                    <td>{{ events.Event_EndDate }}</td>
                    <td>{{ events.Event_EndTime }}</td>
                    <td>{{ events.Event_Requirement }}</td>
                    <td>{{ events.Event_MaxPax }}</td>
                    {% if request.user.is_superuser %}
                    <td><a href="{% url 'event:event_edit' pk=events.pk %}" class="btn btn-warning">Edit</a>
                    <td><a href="{% url 'event:event_delete' pk=events.pk %}"
                           onclick="return confirm('Are you sure you want to delete?')"
                           class="btn btn-danger">Delete</a>
                    </td>
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
                {% if request.user.is_superuser %}
                <div class="row">
                    <div class="col-md-4">
                        <a href="{% url 'event:event_new' %}" class="btn btn-primary">Add Event</a>
                    </div>
                    <div class="col-md-4">
                        <a href="{% url 'event:event_addhours' %}" class="btn btn-primary">Add Hours</a>
                    </div>
                </div>
                {% elif user.is_authenticated %}
                <div class="row">
                    <a href="{% url 'event:staff_addhours' %}" class="btn btn-warning">Add hours</a>
                </div>
                    {% endif %}


    </div>
    </body>
    </html>
{% endblock %}

event/templates/event/event_list_public.html
{% extends 'event/base.html' %}


{% block content %}
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title>Mid-City Gives Back</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    </head>
    <body>
    <style>
        body {
            background-color: beige;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">Welcome!</div>
                    <div class="panel-body">
                        <p>Below is a list of all events.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <h2 style="padding-left: 15Px">Event List</h2>
    </div>
    <div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Event Description</th>
                <th>Event Start Date</th>
                <th>Event Start Time</th>
                <th>Event End Date</th>
                <th>Event End Time</th>
                <th>Event Requirement</th>
                <th>Event Capacity</th>
                <th>Event Address</th>
                <th>Event City</th>
                <th>Event State</th>
            </tr>
            </thead>
            <tbody>
            {% for events in events %}
                <tr>
                    <td>{{ events.Event_Description }}</td>
                    <td>{{ events.Event_StartDate }}</td>
                    <td>{{ events.Event_StartTime }}</td>
                    <td>{{ events.Event_EndDate }}</td>
                    <td>{{ events.Event_EndTime }}</td>
                    <td>{{ events.Event_Requirement }}</td>
                    <td>{{ events.Event_MaxPax }}</td>
                    <td>{{ events.Event_Street }}</td>
                    <td>{{ events.Event_City }}</td>
                    <td>{{ events.Event_State }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    </body>
    </html>
{% endblock %}

event/templates/event/home.html
{% extends 'event/base.html' %}
{% load staticfiles %}
{% block content %}


            {% if user.is_authenticated %}
                <div class="page-container">

                    <h2 class="top-menu">Hello {{ user.username }},</h2>
                    <p>Please choose from below options.</p>
<div class="links">
                    <!-- Example row of columns -->
                    <div class="row">
                        <div class="col-md-4">
                            <div class="thumbnail">
                                <img src="{% static "images/customer.jpg" %}" alt="customer"/>
                                <div class="caption">
                                    <h2>Manage Events</h2>
                                    <p>Employees can add volunteer hours. HR managers can add/update/delete events.</p>
                                    {% if user.is_authenticated %}
                                        <p><a class="btn btn-default" href="{% url 'event:event_list' %}"
                                              role="button">View
                                            details &raquo;</a></p>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        {% if request.user.is_superuser %}
                         <div class="col-md-4">
                            <div class="thumbnail">
                                <img src="{% static "images/stocks.jpg" %}" alt="stocks"/>
                                <div class="caption">
                                    <h2>Manage Organizations</h2>
                                    <p>HR Managers can add/update/delete organizations.</p>
                                    <p><a class="btn btn-default" href="{% url 'event:org_list' %}" role="button">View
                                        details &raquo;</a></p>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                </div>


                </div>
            {% endif %}



    </body>
    </html>
{% endblock %}

event/templates/event/org_delete.html
{% extends "event/base.html" %}

{% block body_block %}
    <h1>Delete {{ org.name }}?</h1>

    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'event:home' pk=org.pk %} ">Cancel</a>

    </form>

{% endblock %}

event/templates/event/org_list.html
{% extends 'event/base.html' %}


{% block content %}
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title>Mid-City Gives Back</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    </head>
    <body>
    <style>
        body {
            background-color: beige;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">Welcome!</div>
                    <div class="panel-body">
                        <p>Below is a list of all organizations.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <h2 style="padding-left: 15Px">Organization List</h2>
    </div>
    <div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Org ID</th>
                <th>Name</th>
                <th>Phone</th>
                <th>Description</th>
                <th>Email</th>
                <th>City</th>
                <th>State</th>
                <th>Contact Person First Name</th>
                <th>Contact Person Last Name</th>
                <th colspan="2">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for orgs in orgs %}
                <tr>
                    <td>{{ orgs.Org_ID }}</td>
                    <td>{{ orgs.Org_Name }}</td>
                    <td>{{ orgs.Org_Phone }}</td>
                    <td>{{ orgs.Org_Description }}</td>
                    <td>{{ orgs.Org_Email }}</td>
                    <td>{{ orgs.Org_City }}</td>
                    <td>{{ orgs.Org_State }}</td>
                    <td>{{ orgs.Org_Name }}</td>
                    <td>{{ orgs.Org_Name }}</td>

                    <td><a href="{% url 'event:org_edit' pk=orgs.pk %}" class="btn btn-warning">Edit</a>
                    <td><a href="{% url 'event:org_delete' pk=orgs.pk %}"
                           onclick="return confirm('Are you sure you want to delete?')"
                           class="btn btn-danger">Delete</a>
                    </td>

                </tr>
            {% endfor %}
            </tbody>
        </table>
             <div class="row">
                    <a href="{% url 'event:org_new' %}" class="row"><span
        {                    class="btn btn-primary">Add Organization</span></a>
                </div>
    </div>
    </body>
    </html>
{% endblock %}

event/templates/event/signup.html
{% extends 'event/base.html' %}

{% block content %}
  <h2>Sign up</h2>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}